### ISSUE TITLE
find_elements_by_model return None if elements are not found instead of empty array

### ISSUE THREAD

**Issue by pulphix** [kpodl/pytractor#10]
The current js script findByModel.js doesn't return anything if elements are not found causing issue on 
find_element_by_model function:
TypeError: object of type 'NoneType' has no len()

This issue affect as well findByOptions

This issue came directly from protactor

**Comment by kpodl** [comment]
Thanks for the bug report. This will be fixed in the next release.

**Comment by pulphix** [comment]
You welcome
