### ISSUE TITLE
wait_for_angular doesn't.

### ISSUE THREAD

**Issue by jimfulton** [kpodl/pytractor#11]
``wait_for_angular`` isn't waiting because it doesn't (and has no way to) pass a callback through ``waitForAngular`` to ``whenStable``.

I have no idea how protractor does this.

I ended up with a helper:

    def wait_ng(self):
        self.browser.execute_script(
            """
            al_angular_stable = false;
            angular.getTestability(document.querySelector('body')).whenStable(
               function () { al_angular_stable = true; }
               )
            """)
        wait(message="Angular to settle")(lambda: self.browser.execute_script("return al_angular_stable"))

Where wait is: https://pypi.python.org/pypi/zope.testing#wait-until-a-condition-holds-or-until-a-time-out

Sadly, this doesn't solve the problem that led me to dig into this. :( So maybe I did it wrong too, but I don't think so.

**Comment by kpodl** [comment]
Thanks for the info. I will look into this.
Can you tell me which angular version you are using?

**Comment by kpodl** [comment]
I think I have found the problem:
protractor's `waitForAngular.js` must be called as an async script. The callback will be provided by selenium to determine whether the script has finished (see: [JavascriptExecutor API Doc](https://selenium.googlecode.com/svn/trunk/docs/api/java/org/openqa/selenium/JavascriptExecutor.html#executeAsyncScript(java.lang.String, java.lang.Object...)) )

Do you have a test case that I can use to verify the solution?
