### ISSUE TITLE
Missing locators?

### ISSUE THREAD

**Issue by bootstraponline** [kpodl/pytractor#3]
It looks like a bunch of features are missing (ex: find by repeater). It'd be nice to document what's available and what isn't.

**Comment by kpodl** [comment]
Yes, sorry about that. Originally, I thought, I would get to implementing the missing features sooner. I will have a look at that.

**Comment by bootstraponline** [comment]
No problem. I was just checking out the project since I noticed the selenium conf presentation.

**Comment by kpodl** [comment]
Added some information about available and missing features to the README.
