### ISSUE TITLE
Launching Url on binary(CEFClient) using Pytractor

### ISSUE THREAD

**Issue by AtulUjjwal** [kpodl/pytractor#4]
Hi,
I want to launch my url on the cefclient.exe using pytractor.
I am able to achieve this using Selenium driver using capabilities(binary), but when using pytractor , i am not able to use this feature.
Please help to resolve this issue.

**Comment by kpodl** [comment]
Sorry, I am not familiar with cefclient.exe. Could you be more specific as to what the actual problem is?

**Comment by AtulUjjwal** [comment]
Hi, 
Resolved the issue. Actually , I was trying to use binary to host a url.
Thanks.
