### ISSUE TITLE
Ability to add angularjs testing support for already existing instance of webdriver 

### ISSUE THREAD

**Issue by pvshewale** [kpodl/pytractor#6]
At present we have angularjs testing support if we create webdriver instance from `pytractor.webdriver`. But most of the time in automation framework that instance is already created by some utility method and it is created from `selenium.webdriver`.

So we may need to have ability to add `WebDriverMixin` as additional base class to already created instance of `selenium.webdriver`. Below utility method can be used for this purpose.

```
from pytractor.mixins import WebDriverMixin
from selenium.webdriver.remote.webdriver import WebDriver

def add_ng_support(instance, base_url, root_element, script_timeout=10, test_timeout=10):
    if issubclass(instance.__class__, WebDriver):
        instance.__class__ = type(instance.__class__.__name__,(WebDriverMixin, instance.__class__),
                              dict(_base_url=base_url, _root_element=root_element, _test_timeout=test_timeout))
        instance.set_script_timeout(script_timeout)
    return instance
```

Above method accepts webdriver object and returns modified object. Can be used as below,

```
from selenium.webdriver import Firefox
driver = Firefox()
ng_driver = add_ng_support(driver, base_url= None, root_element="body")
ng_driver.get("https://docs.angularjs.org/guide/unit-testing")
search = ng_driver.find_element_by_model('q')
search.send_keys('binding')
```

Can you please add this utility method to pytractor/webdriver.py

**Comment by kpodl** [comment]
Thanks for your input and the nice description on how to dynamically add superclasses to instances. This was new to me.
I have given this some thought, but I do not think that such a utility function should be a part of pytractor.
I might consider adding this in the future if there are more requests for such a feature.
