### ISSUE TITLE
Works with non Firefox browsers?

### ISSUE THREAD

**Issue by iainctduncan** [kpodl/pytractor#7]
Sorry if this isn't the place to ask, is pytractor mean to work with all selenium browsers? I seem to be having issues when trying it with PhantomJS and thought I should check if that should even be possible.

**Comment by mwalkowski** [comment]
I have been checked on Chrome,  and it's working fine. I think it should be working because it's only wrapper for python selenium.

**Comment by kpodl** [comment]
Yes, it should work with all selenium browsers. I routinely check Firefox and Chrome, but I do not see any reason why it should not work with others. If you find a problem with a particular selenium driver, please let me know.
