### ISSUE TITLE
Python3 ability add

### ISSUE THREAD

**Issue by mwalkowski** [kpodl/pytractor#8]
When I add support for python3 , you do release it to PyPI ?
Because I need it quickly.

**Comment by kpodl** [comment]
Python 3 support would be very much appreciated! If you add it (and the tests pass) I will try to create a release asap. However, next week is going to be very busy for me, so I cannot promise anything.

**Comment by jimfulton** [comment]
Ok look! There's a Python 3 PR! :) It needs a minor tweak, but with it tests pass for me with Python 2.7 and 3.4.  I too need Python 3 support.

**Comment by kpodl** [comment]
Python 3 support has been added in v0.2.0.
